### ISSUE TITLE
Please delete this repo

### ISSUE THREAD

**Issue by supermarin** [CodeEagle/AutoUpdateDVTPlugInCompatibilityUUID#1]
It has been highly discouraged by Apple to do this.
It's the primary reason why they added UUIDs at the first place.

If people start doing this, there's a chance we'll make them angry and make our lives even harder.

**Comment by CodeEagle** [comment]
yep,I see.But I wander if there is another way to do this?
Such as I provide a UI to display the unload plug-ins and then option to upgrade or not?

**Comment by supermarin** [comment]
The whole idea is that plugin maintainers should check if their plugins are still working or not,
and then update the UUID.

**Comment by supermarin** [comment]
If you update it manually and such a plugin crashes your Xcode,
it's Apple developers that are getting crash reports.

**Comment by CodeEagle** [comment]
yep, I got it.I just thinking about using a standalone app to do this stuff,not a Xcode plug-in.
Thanks for answering.

**Comment by supermarin** [comment]
Thanks @CodeEagle, appreciate that
